pipeline {
    agent {
      label 'chef' // only run on chef node
      }
    stages {
        stage('fetch code'){
        agent {
          label 'chef' // only run on chef node
          }
         steps{
             git credentialsId: 'be857a0bb56d8a8f7ed9dd90a6d9ae8d4876b582', url: 'https://github.com/Ujwal90210/chef_base.git'
         }
        }
        stage('Build') {
        agent {
          label 'chef' // only run on chef node
          }
            steps {
                echo 'Building..'
                sh 'cd cookbooks/chef_base; berks vendor cookbooks' // build cookbook with all dependencies
            }
        }
        stage('Local Tests') {
            steps {
                echo 'Testing..'
              //  sh 'cd cookbooks/chef_base; chef exec rake style:ruby' // run rubocop
                sh 'cd cookbooks/chef_base; chef exec rake style:chef' // run foodcritic
                sh 'foodcritic . --tags ~FC071'
                sh 'cd cookbooks/chef_base; chef exec rake unit' // run ChefSpec tests
            }

        }
        stage('Integration Tests') {
           steps {
                echo 'Integration...'
                // run kitchen test with a concurrency of 2 at a time
                sh 'cd cookbooks/chef_base; chef exec rake integration'
           }
            post {
              always {
                // publish serverspec results
                junit 'serverspec*.xml'
              }
            }
        }
    }
//  post {
//      always {
//         deleteDir() /* clean up our workspace */
//      }
//     }
}
