pipeline {
    agent {
      label 'chef' // only run on chef node

    stages {
        stage('fetch code'){
         steps{
            sh 'ifconfig'
             git credentialsId: 'be857a0bb56d8a8f7ed9dd90a6d9ae8d4876b582', url: 'https://github.com/Ujwal90210/chef_base.git'
         }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'cd /home/ec2-user/workspace/chef_cookbook_build/chef_base/cookbooks/chef_base'
                sh 'berks vendor cookbooks' // build cookbook with all dependencies
            }
        }
        stage('Local Tests') {
            steps {
                echo 'Testing..'
                sh 'chef exec rake style:ruby' // run rubocop
                sh 'chef exec rake style:chef' // run foodcritic
                sh 'chef exec rake unit' // run ChefSpec tests

            }
            post {
              always {
                // use checkstyle plugin to expose rubycop lint checks
                checkstyle canComputeNew: false, canRunOnFailed: true, defaultEncoding: '', healthy: '', pattern: 'int-lint-results.xml', unHealthy: ''
                // use warnings plugin with our custom foodcritic parser to expose chef lint checks
                 warnings canComputeNew: false, canResolveRelativePaths: false, canRunOnFailed: true, consoleParsers: [[parserName: 'Foodcritic']], defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', messagesPattern: '', unHealthy: ''
                // expose chefspec unit tests
                junit 'junit.xml'
                // publish chefspec coverage results
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: '', reportFiles: 'index.html', reportName: 'ChefSpec Report', reportTitles: ''])
              }
            }
        }
        stage('Integration Tests') {
           steps {
                echo 'Integration...'
                // run kitchen test with a concurrency of 2 at a time
                sh 'chef exec rake integration'
           }
            post {
              always {
                // publish serverspec results
                junit 'serverspec*.xml'
              }
            }
        }
    }
    post {
      always {
         deleteDir() /* clean up our workspace */
      }
    }
}
